<?php

const PARAM_FRASE_TELA_INICIAL = 1;
const PARAM_FRASE_SOBRE_NOS = 2;
const PARAM_TITULO_1 = 3;
const PARAM_TITULO_2 = 4;
const PARAM_TITULO_3 = 5;
const PARAM_NOME_ORGANIZACAO = 6;
const PARAM_ICON_LOGO = 8;
const PARAM_FULL_LOGO = 9;
const PARAM_FAV_ICON = 15;
const PARAM_ENDERECO = 10;
const PARAM_SEO_TITLE = 7;
const PARAM_SEO_DESCRICAO = 11;
const PARAM_SEO_AUTHOR = 12;
const PARAM_SEO_KEYWORDS = 13;
const PARAM_NOS_ENCONTRE_ONLINE = 14;
